// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@gophkeeper.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "Проверяет доступность сервера и подключение к БД",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "monitoring"
                ],
                "summary": "Проверка здоровья сервера",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/secret": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Создает секрет текущего авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Создание секрета пользователя",
                "parameters": [
                    {
                        "description": "Данные секрета",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.SecretCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешное создание секрета"
                    },
                    "400": {
                        "description": "Неверный запрос"
                    },
                    "401": {
                        "description": "Пользователь не авторизован"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/secret/batch": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Синхронизирует батч локальных секретов клиента с сервером",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Батчевая синхронизация секретов",
                "parameters": [
                    {
                        "description": "Батч секретов для синхронизации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.BatchSyncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная синхронизация",
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.BatchSyncResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос"
                    },
                    "401": {
                        "description": "Пользователь не авторизован"
                    },
                    "413": {
                        "description": "Слишком большой батч (\u003e100 секретов)"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/secret/file": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загружает файл как секрет пользователя",
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Загрузка файлового секрета",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Файл для загрузки",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "TEXT",
                            "CARD",
                            "FILE",
                            "CREDENTIALS"
                        ],
                        "type": "string",
                        "default": "FILE",
                        "description": "Тип секрета",
                        "name": "data_type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "example": "{\"login\":\"user\",\"password\":\"pass\"}",
                        "description": "Данные секрета в JSON формате",
                        "name": "data",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешная загрузка файла"
                    },
                    "400": {
                        "description": "Неверный запрос"
                    },
                    "401": {
                        "description": "Пользователь не авторизован"
                    },
                    "413": {
                        "description": "Файл слишком большой"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/secret/list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает список всех сохраненных секретов (данных) текущего авторизованного пользователя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Получение списка секретов пользователя",
                "responses": {
                    "200": {
                        "description": "Успешное получение списка секретов",
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.SecretListResponse"
                        }
                    },
                    "204": {
                        "description": "Нет содержимого (список секретов пуст)"
                    },
                    "401": {
                        "description": "Пользователь не авторизован"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/secret/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает секрет текущего авторизованного пользователя по id секрета",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Получение секрета пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID секрета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное получение секрета",
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.SecretResponse"
                        }
                    },
                    "204": {
                        "description": "Секрет не найден"
                    },
                    "400": {
                        "description": "Неверный запрос"
                    },
                    "401": {
                        "description": "Пользователь не авторизован"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Обновляет существующий секрет текущего авторизованного пользователя по id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Обновление секрета пользователя",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID секрета",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Обновленные данные секрета",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.SecretUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное обновление секрета",
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.SecretResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос"
                    },
                    "401": {
                        "description": "Пользователь не авторизован"
                    },
                    "403": {
                        "description": "Доступ запрещен (секрет принадлежит другому пользователю)"
                    },
                    "404": {
                        "description": "Секрет не найден"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Вход в систему с получением JWT токена",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Аутентификация пользователя",
                "parameters": [
                    {
                        "description": "Учетные данные пользователя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.AuthUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешный вход, токен в cookie и теле ответа",
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или пустые поля"
                    },
                    "401": {
                        "description": "Неверный логин или пароль"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Создает нового пользователя с указанным логином и паролем",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация нового пользователя",
                "parameters": [
                    {
                        "description": "Данные для регистрации",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.AuthUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация, токен в cookie и теле ответа",
                        "schema": {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или пустые поля"
                    },
                    "409": {
                        "description": "Пользователь с таким логином уже существует"
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_mdflamingo_GophKeeper_internal_model.AuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.AuthUser": {
            "type": "object",
            "required": [
                "login",
                "password"
            ],
            "properties": {
                "login": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 3,
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 6,
                    "example": "strongpassword123"
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.BatchSecret": {
            "type": "object",
            "required": [
                "data",
                "data_type",
                "local_id",
                "local_version"
            ],
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "data_type": {
                    "enum": [
                        "TEXT",
                        "FILE",
                        "CARD",
                        "CREDENTIALS"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.DataType"
                        }
                    ]
                },
                "local_id": {
                    "type": "integer"
                },
                "local_version": {
                    "type": "integer"
                },
                "server_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.BatchStats": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "integer"
                },
                "failed": {
                    "type": "integer"
                },
                "processed": {
                    "type": "integer"
                },
                "updated": {
                    "type": "integer"
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.BatchSyncError": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "local_id": {
                    "type": "integer"
                },
                "server_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.BatchSyncRequest": {
            "type": "object",
            "properties": {
                "secrets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.BatchSecret"
                    }
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.BatchSyncResponse": {
            "type": "object",
            "properties": {
                "failed": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.BatchSyncError"
                    }
                },
                "stats": {
                    "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.BatchStats"
                },
                "success": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.BatchSyncResult"
                    }
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.BatchSyncResult": {
            "type": "object",
            "properties": {
                "local_id": {
                    "type": "integer"
                },
                "server_id": {
                    "type": "integer"
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.DataType": {
            "type": "string",
            "enum": [
                "TEXT",
                "CARD",
                "FILE",
                "CREDENTIALS"
            ],
            "x-enum-varnames": [
                "TEXT",
                "CARD",
                "FILE",
                "CREDENTIALS"
            ]
        },
        "github_com_mdflamingo_GophKeeper_internal_model.SecretCreateRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "data_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.DataType"
                        }
                    ],
                    "example": "CREDENTIALS"
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.SecretListResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "secrets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.SecretResponse"
                    }
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.SecretResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00Z"
                },
                "data_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.DataType"
                        }
                    ],
                    "example": "CREDENTIALS"
                },
                "id": {
                    "type": "integer",
                    "example": 5
                },
                "meta_data": {
                    "type": "object"
                }
            }
        },
        "github_com_mdflamingo_GophKeeper_internal_model.SecretUpdateRequest": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object"
                },
                "data_type": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/github_com_mdflamingo_GophKeeper_internal_model.DataType"
                        }
                    ],
                    "example": "CREDENTIALS"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "GophKeeper API",
	Description:      "API сервиса GophKeeper для безопасного хранения данных",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
